version: '3.9'

services:
  inp-backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - django_static_volume:/var
    depends_on:
      - inp-db
    env_file:
      - .env
    entrypoint: ${DJANGO_ENTRYPOINT-python manage.py runserver 0.0.0.0:8000}
    networks:
      - docker-network
    profiles:
      - prod
      - dev
    restart: always

  inp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    entrypoint: ${REACT_ENTRYPOINT-npm start}
    networks:
      - docker-network
    profiles:
      - prod
      - dev
    restart: always

  inp-db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - docker-network
    profiles:
      - prod
      - dev
    restart: always

networks:
  docker-network:
    external: true

volumes:
  pg_data:
  django_static_volume:

