version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/backend/dev.env
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - ENV=development
    env_file:
      - ./frontend/dev.env
    entrypoint: ["npm", "start"]

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/backend/dev.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
