# Generated by Django 4.1.5 on 2023-02-08 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('business', 'Business'), ('health', 'Health'), ('opinion', 'Opinion'), ('politics', 'Politics'), ('science', 'Science'), ('sports', 'Sports'), ('style', 'Style'), ('technology', 'Technology'), ('travel', 'Travel')], default='business', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='photos/')),
                ('excerpt', models.CharField(blank=True, max_length=150)),
                ('month', models.CharField(blank=True, max_length=3)),
                ('day', models.CharField(blank=True, max_length=2)),
                ('content', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('image_position', models.CharField(blank=True, choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=15)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('generate_content', models.BooleanField(default=False)),
            ],
        ),
    ]
