# Generated by Django 4.1.5 on 2023-01-22 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('opinion', 'Opinion'), ('science', 'Science'), ('health', 'Health'), ('style', 'Style'), ('travel', 'Travel')], default='world', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='photos/')),
                ('excerpt', models.CharField(blank=True, max_length=150)),
                ('month', models.CharField(blank=True, max_length=3)),
                ('day', models.CharField(blank=True, max_length=2)),
                ('content', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
