# Generated by Django 4.1.5 on 2023-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('business', 'Business'), ('health', 'Health'), ('opinion', 'Opinion'), ('science', 'Science'), ('sports', 'Sports'), ('style', 'Style'), ('technology', 'Technology'), ('programming', 'Programming'), ('travel', 'Travel')], default='business', max_length=50),
        ),
    ]
